version: '3.8'

services:
  elpe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elpe
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elpe.rule=Host(`elpe.alexvplle.com`)"
      - "traefik.http.routers.elpe.entrypoints=websecure"
      - "traefik.http.services.elpe.loadbalancer.server.port=3000"

networks:
  traefik_network:
    external: true
